### ISSUE TITLE
fp-ts

### ISSUE THREAD

**Issue by goodmind** [TylorS/typed#1]
Why you are not using https://github.com/gcanti/fp-ts ?

**Comment by TylorS** [comment]
No reason in particular. I just like to learn things by taking the time to implement them myself 😀

I've actually been using fp-ts as a source of inspiration!

**Comment by TylorS** [comment]
Another small goal is avoid classes and to make these data-structures small and JSON-serializable.

**Comment by TylorS** [comment]
In the end I merged my library [`167`](https://github.com/TylorS167/167) into this repository, which is much more ramda-esque, and broke it into smaller packages that makes use of things like Maybe/Either.  I definitely see this repository and `fp-ts` as libraries that can be used together :)
