### ISSUE TITLE
Add propOr

### ISSUE THREAD

**Issue by Frikki** [TylorS/typed#19]

**Comment by TylorS** [comment]
What do you think about parameter order? 
```typescript
propOr<O extends object, K extends keyof O>(key: K, defaultValue: O[K], obj: O): O[K] 
// or
 propOr<O extends object, K extends keyof O>(defaultValue: O[K], key: K, obj: O): O[K] 
```

I think I favor the latter because the `defaultValue` should probably dictate which key you need from the objects you have and will generally be better for composition.

**Comment by Frikki** [comment]
Yes, latter.
