### ISSUE TITLE
Can't `.map` output from groupBy

### ISSUE THREAD

**Issue by radicand** [TylorS/typed#45]
`groupBy` casts its value output as ArrayLike (via List), which lacks operators like `map`, `filter`, `reduce`, etc. Is there a reason for this, or another recommended way to be able to do something similar to the below?

```ts
const toGroup = [....];
const grouped = groupBy((item) => ..., toGroup);
grouped.exampleGroupKey.map(x => ...);
```

**Comment by TylorS** [comment]
Hello @radicand thanks for dropping by. The original thought behind this was to enforce immutability at the type level, via List/ArrayLike, which are 100% `readonly` in TypeScript.

In general, there are free-function equivalents available such as `map` and `filter` which you can use instead, which do exactly the same thing - many of them are actually a little faster than the Array.prototype built-ins.

**Comment by radicand** [comment]
Thanks for the explanation @TylorS , that makes sense. I'll use the equivalents as you note.

**Comment by TylorS** [comment]
I hope you enjoy using the library! Don't hesitate to open more issues 😄
