### ISSUE TITLE
@typed/core link returns 404

### ISSUE THREAD

**Issue by Kinrany** [TylorS/typed#74]
The [`@typed/core`](https://github.com/TylorS/typed/blob/master/packages/core) link in the README returns 404. Looks like the package was moved?

**Comment by Frikki** [comment]
That is correct. The package is removed. README needs to be updated. Thanks for the heads-up.

**Comment by TylorS** [comment]
I've been lazy and didn't make this simple change for a long time - it's been removed from the main README
