### ISSUE TITLE
Issue importing from @typed/objects

### ISSUE THREAD

**Issue by moneydance** [TylorS/typed#85]
👋 Hi, awesome library, found this after fighting with the typings for ramda.

While importing prop and set I keep getting errors in my compiled code pointing to prop and set being undefined. 

I believe hasOwnProperty is causing issues in the @typed/objects package when compiled from typescript to javascript.

```
function __export(m) {
  for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p]
}
Object.defineProperty(exports, '__esModule', { value: true })
__export(require('./clone'))
__export(require('./hasOwnProperty'))
__export(require('./invoker'))
// ...etc
```

I stepped through this code and noticed that everything after calling __export on hasOwnProperty isn't added to the exports object.

I believe this is because the native hasOwnProperty implementation on the exports object is being replaced by the curried hasOwnProperty function provided by @typed/objects. The check then fails since a function is always returned. I think a quick fix would be moving the export hasOwnProperty to the end of the exports in https://github.com/TylorS/typed/blob/master/packages/objects/src/index.ts

If you'd like a minimal reproducible repo I can provide one. I can also put up a quick PR to move the export if you'd like.

**Comment by TylorS** [comment]
Hey @moneydance thanks for the issue. I started this project also after fighting with typings and ramda and wanted es2015 builds before rambda had them as well. I mostly make use of the es2015 builds so I haven't run across this error but your debugging makes plenty of sense. 

I'd happily accept a PR for the fix you suggest. I'd only ask that you test the change out before if you haven't already. Thanks!
